### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by heffernan66** [ihofmann/open-websoccer#43]
Hi,
I installed an new game and the installation works fine. but I cannot login as an admin there comes this message.

You need to log in!
Please provide your credentials below.

I hav the correct Username and password and i can create and login as an player

**Comment by RahmanAnsari** [comment]
yea! i'm facing the same issue.. Planning to install the old version...

**Comment by rolfjoseph** [comment]
You are use PHP 7, this Version needs PHP 5.

You can use it at PHP 7, but unter PHP 7 they are many changes, so the use of this websoccer can be broken his work. Under PHP 7.2 brokes the session-handling with the database.

**Comment by mister1966** [comment]
hi,
i'm using 5.6.40 (the minimux available) but i'm still locked to AdminCenter Log-In....

**Comment by nafbanap** [comment]
The admin center should work with the version 5.6.40.
Maybe you have multiple versions running, like with fpm and cli?
Apart from that, would a fix for PHP 7 be an option for you?

**Comment by mister1966** [comment]
hi nafbanap, 
thks for reply, i'm starting just now with this software....
is there a complete version for php7?

**Comment by nafbanap** [comment]
There are/were versions available that worked with PHP7.
For example, the tlc-version. But they became less compatible with the original release.
I'll post a commit to fix the login for the ACP. If you want, you can try my fork, which contains a few more fixes.

**Comment by mister1966** [comment]
ok installed every thing and started in local webserver to understand how the game is working.
i create 4 leagues, matches, players, cups and national teams...
just a question: around internet i see a lot of version (acta2000 in php-7 seems good but i'm not able to install on my pc, i got some errors at the installation although i setup xampp with php7)...
otherwise tlc is good?
thks in advance

**Comment by nafbanap** [comment]
Depends on what you need. Most forks have poor or no commentary on the code, which makes future adjustments difficult. Also, the TLC versions in particular have thrown out any compatibility with other development lines. This means that a use of these versions can be right if you need some special features of them and a) have plenty of coding skills yourself or b) don't plan any more customizations at any time.
I have decided not to use one of these versions because I consider the above mentioned disadvantages to be a hindrance. If there would have been a version that from a simulation point of view would have had well thought-out improvements to the original, this would probably have been exciting, but that was not the case.

**Comment by mister1966** [comment]
yes i'm agree with you so i decide to continue with this version....
the simulation is user friendly and in few days i understood a lot of things...
i see in the live sim, action are updates every 60 seconds for how many actions you decide in simulation setup (for expert). Is it possible to set update every 10 seconds? so i will set 1 action for every minute but every minute is updated every 10 seconds....
thks nafbanap

**Comment by dannyx93** [comment]
I also modify this game in my own way. I have added some improvements and sharing them on github. I successfully launched the game, but on php 5.6

**Comment by nafbanap** [comment]
> yes i'm agree with you so i decide to continue with this version....
> the simulation is user friendly and in few days i understood a lot of things...
> i see in the live sim, action are updates every 60 seconds for how many actions you decide in simulation setup (for expert). Is it possible to set update every 10 seconds? so i will set 1 action for every minute but every minute is updated every 10 seconds....
> thks nafbanap

What do you gain from the 10s update window? If you run several simulations at once, such an update frequency will not increase the stability of the process. From a technical point of view, updates in the microsecond range should be possible.
