### ISSUE TITLE
Big matchreport table size

### ISSUE THREAD

**Issue by dannyx93** [ihofmann/open-websoccer#75]
I noticed that the match report generates a lot of data into the database. Maybe someone knows how to optimize this table?

**Comment by nafbanap** [comment]
That depends on what needs to be optimized.
When it comes to load times, suitable database indexes are particularly important.
If the unlikely reason is that you need to save on database memory, you could customize the script so that when you generate the match report, you don't save the text templates completely in the report, but only short codes with parameters and then when you output the whole thing, the report is recreated on PHP level. This should work well with all text modules and graphic elements.

**Comment by dannyx93** [comment]
I am currently manually removing old match reports from the database.
